sudo: required
dist: xenial
language: node_js
node_js:
  - "6"
services:
  - xvfb
source:
  - google-chrome

before_install:
  - export DISPLAY=:99.0
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation

before_script:
  - npm install -g gulp
  - npm install -g karma-cli
  - gulp
script: karma start --single-run