language: node_js
node_js:
  - "0.12"
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - npm install -g karma-cli
  - gulp
script: karma start --single-run
